house_rent/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tolet.urls')),
]

tolet/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('blog/', views.blog, name='blog'),
    path('blog_details/<slug:slug>/', views.blog_details, name='blog_details'),
    path('service/', views.service, name='service'),
    path('room/', views.room, name='room'),
    path('room_details/<int:id>/', views.room_details, name='room_details'),
    path('booking/', views.booking, name='booking'),
    path('testimonial/', views.testimonial, name='testimonial'),
    path('team/', views.team, name='team'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('subscribe-newsletter/', views.subscribe_newsletter, name='subscribe_newsletter'),
    path('create_post/', views.create_post, name='create_post'),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tolet/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from location_field.models.plain import PlainLocationField
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.
class Member(models.Model):
    firstname=models.CharField(max_length=255)
    lastname=models.CharField(max_length=255)
    phone=models.IntegerField(null=True)
    joined_date=models.DateField(null=True)
    slug=models.SlugField(default="", null=False)

    def __str__(self):
        return f'{self.firstname} {self.lastname}'

class BlogPost(models.Model):
    title=models.CharField(max_length=200)
    content=models.TextField()
    image = models.ImageField(upload_to='images/', null=True, blank=False)
    author=models.ForeignKey(User, on_delete=models.CASCADE)
    date_post=models.DateTimeField(default=timezone.now)
    slug=models.SlugField(default="", null=False)
    latitude = models.DecimalField(
        max_digits=9, decimal_places=6, null=True, blank=True,
        validators=[MinValueValidator(-90), MaxValueValidator(90)]
    )
    longitude = models.DecimalField(
        max_digits=9, decimal_places=6, null=True, blank=True,
        validators=[MinValueValidator(-180), MaxValueValidator(180)]
    )
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f'{self.title}'

class family_flat(models.Model):
    flat_owner=models.ForeignKey(User, on_delete=models.CASCADE)
    title=models.CharField(max_length=200,default="TOLET")
    images=models.ImageField(upload_to='images/', null=False, blank=False)
    number_of_floor=models.IntegerField()
    total_number_of_room=models.IntegerField()
    number_of_masterbed=models.IntegerField()
    number_of_washroom=models.IntegerField()
    drowing_room=models.BooleanField()
    dining_room=models.BooleanField()
    lift_facility=models.BooleanField()
    GAS_CHOICES = [
        ('Cylinder Gas', 'Cylinder Gas'),
        ('Line Gas', 'Line Gas')
    ]
    gas_system = models.CharField(
        max_length=20,  # The length of 'M', 'F', or 'O' is 1 character
        choices=GAS_CHOICES,  # Use the GENDER_CHOICES defined above
        null=False, blank=False
    )

    gas_electric_bill_attach_with_price=models.BooleanField()
    price=models.IntegerField()
    phone_number=models.CharField(max_length=200, null=False, blank=False)
    rent_date=models.DateField(default=timezone.now)
    address=models.CharField(max_length=200, null=False, blank=False)
    location = PlainLocationField(based_fields=['city'], zoom=7)

    def __str__(self) -> str:
        return f'{self.title} :Total room {self.total_number_of_room} from {self.rent_date}'

class bachalor_flat(models.Model):
    flat_owner=models.ForeignKey(User, on_delete=models.CASCADE)
    title=models.CharField(max_length=200,default="TOLET")
    images=models.ImageField(upload_to='images/', null=False, blank=False)

    GENDER_CHOICES = [
        ('MALE', 'Male'),
        ('FEMALE', 'Female'),
        ('OTHER', 'Other'),
    ]
    gender = models.CharField(
        max_length=20,  # The length of 'M', 'F', or 'O' is 1 character
        choices=GENDER_CHOICES,  # Use the GENDER_CHOICES defined above
        null=False, blank=False
    )

    number_of_floor=models.IntegerField()
    number_of_room=models.IntegerField()
    number_of_seat=models.IntegerField()
    number_of_masterbed=models.BooleanField()
    lift_facility=models.BooleanField()
    gas_electric_bill_attach_with_price=models.BooleanField()
    washroom_CHOICES = [
        ('ATTACH', 'Attach'),
        ('COMMON', 'Common'),
    ]
    washroom_type = models.CharField(
        max_length=10,  # The length of 'M', 'F', or 'O' is 1 character
        choices=washroom_CHOICES,  # Use the GENDER_CHOICES defined above
        null=False, blank=False
    )
    FOOD_CHOICES = [
        ('Meal', 'Meal'),
        ('Fixed Meal', 'Fixed Meal'),
        ('Other System', 'Ohter System')
    ]
    food_system = models.CharField(
        max_length=20,  # The length of 'M', 'F', or 'O' is 1 character
        choices=FOOD_CHOICES,  # Use the GENDER_CHOICES defined above
        null=False, blank=False
    )
    drowing_room=models.BooleanField()
    dining_room=models.BooleanField()
    price_per_room=models.IntegerField(null=True, blank=True)
    price_per_seat=models.IntegerField(null=True, blank=True)
    phone_number=models.CharField(max_length=200, null=False, blank=False)
    rent_date=models.DateField(default=timezone.now)
    address=models.CharField(max_length=200, null=False, blank=False)
    location = PlainLocationField(based_fields=['city'], zoom=7)

    def __str__(self) -> str:
        return f'{self.title} :Totel for {self.gender} from {self.rent_date} in {self.address}'

class Subscriber(models.Model):
    email = models.EmailField(unique=True)
    subscribed_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email

tolet/forms.py
from django import forms
from .models import BlogPost, family_flat, bachalor_flat, Subscriber
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'content', 'image','slug','date_post', 'latitude', 'longitude']  # Include the image field in the form
        widgets = {
            'latitude': forms.HiddenInput(),
            'longitude': forms.HiddenInput(),
        }

class family_flat_Form(forms.ModelForm):
    image = forms.ImageField()  # Allow multiple images

    class Meta:
        model = family_flat
        fields = ['flat_owner','title','number_of_floor','total_number_of_room','number_of_masterbed','number_of_washroom','drowing_room','dining_room','price','phone_number','rent_date','address','location','images','lift_facility','gas_electric_bill_attach_with_price','gas_system']

class bachalor_flat_Form(forms.ModelForm):
    image = forms.ImageField()  # Allow multiple images

    class Meta:
        model = bachalor_flat
        fields = ['flat_owner','title','number_of_floor','number_of_room','number_of_seat','number_of_masterbed','price_per_seat','drowing_room','dining_room','price_per_room','phone_number','rent_date','address','location','images','lift_facility','gas_electric_bill_attach_with_price','gender','washroom_type','food_system']

class SubscriberForm(forms.ModelForm):
    class Meta:
        model = Subscriber
        fields = ['email']

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

tolet/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.template import loader
from .models import *
from .forms import SubscriberForm, UserRegisterForm,BlogPostForm
from django.core.mail import send_mail
from django.conf import settings
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.core.validators import validate_email
from django.core.exceptions import ValidationError

# Create your views here.
def members(request):
    mymembers= Member.objects.all().values()
    template=loader.get_template('all_members.html')
    context = {
        'mymembers':mymembers,
    }
    return HttpResponse(template.render(context, request))

def details(request, slug):
    mymember=Member.objects.get(slug=slug)
    template=loader.get_template('details.html')
    context = {
        'mymember':mymember,
    }
    return HttpResponse(template.render(context,request))

def main(request):
    template = loader.get_template('main.html')
    return HttpResponse(template.render())

def testing(request):
    mymembers=Member.objects.all().order_by('firstname','-slug').values
    template=loader.get_template('template.html')
    context = {
        'mymembers':mymembers,
    }
    return HttpResponse(template.render(context,request))

def index(request):
    if request.method == 'POST':
        form = SubscriberForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'index.html')  # Show a thank you page
    else:
        form = SubscriberForm()

    bachalor_posts = bachalor_flat.objects.all().order_by('-rent_date')
    posts=BlogPost.objects.all().order_by('-date_post')
    rooms=family_flat.objects.all().order_by('-rent_date')
    template=loader.get_template('index.html')
    context = {
        'posts':posts,
        'rooms':rooms,
        'b_room':bachalor_posts,
        'form': form,
    }
    return HttpResponse(template.render(context, request))

def about(request):
    template=loader.get_template('about.html')
    return HttpResponse(template.render())

def contact(request):
    if request.method == "POST":
        name = request.POST.get('name')
        email = request.POST.get('email')
        subject = request.POST.get('subject')
        message = request.POST.get('message')

        # Use Django's send_mail function to send the email
        send_mail(
            subject=f'New contact form submission: {subject}',
            message=f'From: {name}\nEmail: {email}\n\nMessage:\n{message}',
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=['soheltanvrir925@gmail.com'],
            fail_silently=False,
            #auth token: vdxg qaom acuy ibhv
        )

        # You can add a success message or redirect here
        return render(request, 'contact.html', {'success_message': 'Your message has been sent successfully!'})
        #return render(request, 'contact.html', {'message_sent': True})

    return render(request, 'contact.html', {'message_sent': False})
    #return render(request, 'contact.html', {})

def booking(request):
    template=loader.get_template('booking.html')
    return HttpResponse(template.render())

def testimonial(request):
    template=loader.get_template('testimonial.html')
    return HttpResponse(template.render())

def team(request):
    template=loader.get_template('team.html')
    return HttpResponse(template.render())

def blog(request):
    posts=BlogPost.objects.all().order_by('-date_post')
    template=loader.get_template('blog.html')
    context = {
        'posts':posts,
    }
    return HttpResponse(template.render(context, request))

def create_post(request):
    if request.method == 'POST':
        form = BlogPostForm(request.POST)
        if form.is_valid():
            user_post = form.save(commit=False)
            user_post.user = request.user
            user_post.save()
            return redirect('index.html')  # Redirect to a success page
    else:
        form = BlogPostForm()
    return render(request,'create_post.html', {'form': form})

def blog_details(request, slug):
    post = get_object_or_404(BlogPost, slug=slug)
    return render(request, 'blog_details.html', {'post': post})

def service(request):
    template=loader.get_template('service.html')
    return HttpResponse(template.render())

def room(request):
    rooms=family_flat.objects.all().order_by('-rent_date')
    template=loader.get_template('room.html')
    context={
        'rooms': rooms,
    }
    return HttpResponse(template.render(context, request))

def room_details(request, id):
    details=family_flat.objects.get(id=id)
    template=loader.get_template('room_details.html')
    context={
        'room': details
    }
    return HttpResponse(template.render(context, request))


@csrf_exempt
def subscribe_newsletter(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        try:
            # Validate email
            validate_email(email)
            # Here, save email to your database or mailing list
            # Example:
            # NewsletterSubscriber.objects.create(email=email)
            
            return JsonResponse({'status': 'success', 'message': 'Thank you for subscribing!'})
        except ValidationError:
            return JsonResponse({'status': 'error', 'message': 'Please enter a valid email address.'})
    return JsonResponse({'status': 'error', 'message': 'Invalid request method.'})

def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Registration successful.")
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'register.html', {'form': form})

# Login View
def user_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('index')
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid form submission.")
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})

# Logout View
def user_logout(request):
    logout(request)
    return redirect('index')

tolet/templates/about.html
{% extends 'master.html' %}
{% load static %}
{% block title %}
  About Us
{% endblock %}
{% block content %}
{% load static %}
  <div class="container-xxl bg-white p-0">
    <!-- Header Start -->
    {% include 'header.html' %}
    <!-- Header End -->

    <!-- Page Header Start -->
    <div class="container-fluid page-header mb-5 p-0" style="background-image: url("{% static 'images/carousel-1.jpg' %}");">
      <div class="container-fluid page-header-inner py-5">
        <div class="container text-center pb-5">
          <h1 class="display-3 text-white mb-3 animated slideInDown">About Us</h1>
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb justify-content-center text-uppercase">
              <li class="breadcrumb-item">
                <a href="#">Home</a>
              </li>
              <li class="breadcrumb-item">
                <a href="#">Pages</a>
              </li>
              <li class="breadcrumb-item text-white active" aria-current="page">About</li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
    <!-- Page Header End -->

    <!-- Booking Start -->
    <div class="container-fluid booking pb-5 wow fadeIn" data-wow-delay="0.1s">
      <div class="container">
        <div class="bg-white shadow" style="padding: 35px;">
          <div class="row g-2">
            <div class="col-md-10">
              <div class="row g-2">
                <div class="col-md-3">
                  <div class="date" id="date1" data-target-input="nearest">
                    <input type="text" class="form-control datetimepicker-input" placeholder="Check in" data-target="#date1" data-toggle="datetimepicker" />
                  </div>
                </div>
                <div class="col-md-3">
                  <div class="date" id="date2" data-target-input="nearest">
                    <input type="text" class="form-control datetimepicker-input" placeholder="Check out" data-target="#date2" data-toggle="datetimepicker" />
                  </div>
                </div>
                <div class="col-md-3">
                  <select class="form-select">
                    <option selected>Adult</option>
                    <option value="1">Adult 1</option>
                    <option value="2">Adult 2</option>
                    <option value="3">Adult 3</option>
                  </select>
                </div>
                <div class="col-md-3">
                  <select class="form-select">
                    <option selected>Child</option>
                    <option value="1">Child 1</option>
                    <option value="2">Child 2</option>
                    <option value="3">Child 3</option>
                  </select>
                </div>
              </div>
            </div>
            <div class="col-md-2">
              <button class="btn btn-primary w-100">Submit</button>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Booking End -->

    <!-- About Start -->
    <div class="container-xxl py-5">
      <div class="container">
        <div class="row g-5 align-items-center">
          <div class="col-lg-6">
            <h6 class="section-title text-start text-primary text-uppercase">About Us</h6>
            <h1 class="mb-4">Welcome to <span class="text-primary text-uppercase">ToLet</span></h1>
            <p class="mb-4">Tempor erat elitr rebum at clita. Diam dolor diam ipsum sit. Aliqu diam amet diam et eos. Clita erat ipsum et lorem et sit, sed stet lorem sit clita duo justo magna dolore erat amet</p>
            <div class="row g-3 pb-4">
              <div class="col-sm-4 wow fadeIn" data-wow-delay="0.1s">
                <div class="border rounded p-1">
                  <div class="border rounded text-center p-4">
                    <i class="fa fa-hotel fa-2x text-primary mb-2"></i>
                    <h2 class="mb-1" data-toggle="counter-up">1234</h2>
                    <p class="mb-0">Rooms</p>
                  </div>
                </div>
              </div>
              <div class="col-sm-4 wow fadeIn" data-wow-delay="0.3s">
                <div class="border rounded p-1">
                  <div class="border rounded text-center p-4">
                    <i class="fa fa-users-cog fa-2x text-primary mb-2"></i>
                    <h2 class="mb-1" data-toggle="counter-up">1234</h2>
                    <p class="mb-0">Staffs</p>
                  </div>
                </div>
              </div>
              <div class="col-sm-4 wow fadeIn" data-wow-delay="0.5s">
                <div class="border rounded p-1">
                  <div class="border rounded text-center p-4">
                    <i class="fa fa-users fa-2x text-primary mb-2"></i>
                    <h2 class="mb-1" data-toggle="counter-up">1234</h2>
                    <p class="mb-0">Clients</p>
                  </div>
                </div>
              </div>
            </div>
            <a class="btn btn-primary py-3 px-5 mt-2" href="">Explore More</a>
          </div>
          <div class="col-lg-6">
            <div class="row g-3">
              <div class="col-6 text-end">
                <img class="img-fluid rounded w-75 wow zoomIn" data-wow-delay="0.1s" src="{% static 'images/about-1.jpg' %}" style="margin-top: 25%;" />
              </div>
              <div class="col-6 text-start">
                <img class="img-fluid rounded w-100 wow zoomIn" data-wow-delay="0.3s" src="{% static 'images/about-2.jpg' %}" />
              </div>
              <div class="col-6 text-end">
                <img class="img-fluid rounded w-50 wow zoomIn" data-wow-delay="0.5s" src="{% static 'images/about-3.jpg' %}" />
              </div>
              <div class="col-6 text-start">
                <img class="img-fluid rounded w-75 wow zoomIn" data-wow-delay="0.7s" src="{% static 'images/about-4.jpg' %}" />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- About End -->

    <!-- Team Start -->
    <div class="container-xxl py-5">
      <div class="container">
        <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
          <h6 class="section-title text-center text-primary text-uppercase">Our Team</h6>
          <h1 class="mb-5">Explore Our <span class="text-primary text-uppercase">Staffs</span></h1>
        </div>
        <div class="row g-4">
          <div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
            <div class="rounded shadow overflow-hidden">
              <div class="position-relative">
                <img class="img-fluid" style="height: 336px; width: 336;" src="{% static 'images/sohel-2.jpg' %}" alt="" />
                <div class="position-absolute start-50 top-100 translate-middle d-flex align-items-center">
                  <a class="btn btn-square btn-primary mx-1" href=""><i class="fab fa-facebook-f"></i></a>
                  <a class="btn btn-square btn-primary mx-1" href=""><i class="fab fa-twitter"></i></a>
                  <a class="btn btn-square btn-primary mx-1" href=""><i class="fab fa-instagram"></i></a>
                </div>
              </div>
              <div class="text-center p-4 mt-3">
                <h5 class="fw-bold mb-0">Tanvir</h5>
                <small>DevOps Engineer</small>
              </div>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.3s">
            <div class="rounded shadow overflow-hidden">
              <div class="position-relative">
                <img class="img-fluid" src="{% static 'images/team-2.jpg' %}" alt="" />
                <div class="position-absolute start-50 top-100 translate-middle d-flex align-items-center">
                  <a class="btn btn-square btn-primary mx-1" href=""><i class="fab fa-facebook-f"></i></a>
                  <a class="btn btn-square btn-primary mx-1" href=""><i class="fab fa-twitter"></i></a>
                  <a class="btn btn-square btn-primary mx-1" href=""><i class="fab fa-instagram"></i></a>
                </div>
              </div>
              <div class="text-center p-4 mt-3">
                <h5 class="fw-bold mb-0">David</h5>
                <small>Developer</small>
              </div>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.5s">
            <div class="rounded shadow overflow-hidden">
              <div class="position-relative">
                <img class="img-fluid" src="{% static 'images/team-3.jpg' %}" alt="" />
                <div class="position-absolute start-50 top-100 translate-middle d-flex align-items-center">
                  <a class="btn btn-square btn-primary mx-1" href=""><i class="fab fa-facebook-f"></i></a>
                  <a class="btn btn-square btn-primary mx-1" href=""><i class="fab fa-twitter"></i></a>
                  <a class="btn btn-square btn-primary mx-1" href=""><i class="fab fa-instagram"></i></a>
                </div>
              </div>
              <div class="text-center p-4 mt-3">
                <h5 class="fw-bold mb-0">Fredrik</h5>
                <small>Designer</small>
              </div>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.7s">
            <div class="rounded shadow overflow-hidden">
              <div class="position-relative">
                <img class="img-fluid" src="{% static 'images/team-4.jpg' %}" alt="" />
                <div class="position-absolute start-50 top-100 translate-middle d-flex align-items-center">
                  <a class="btn btn-square btn-primary mx-1" href=""><i class="fab fa-facebook-f"></i></a>
                  <a class="btn btn-square btn-primary mx-1" href=""><i class="fab fa-twitter"></i></a>
                  <a class="btn btn-square btn-primary mx-1" href=""><i class="fab fa-instagram"></i></a>
                </div>
              </div>
              <div class="text-center p-4 mt-3">
                <h5 class="fw-bold mb-0">David Worner</h5>
                <small>Designer</small>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Team End -->

    <!-- Newsletter Start -->
    <div class="container newsletter mt-5 wow fadeIn" data-wow-delay="0.1s">
      <div class="row justify-content-center">
        <div class="col-lg-10 border rounded p-1">
          <div class="border rounded text-center p-1">
            <div class="bg-white rounded text-center p-5">
              <h4 class="mb-4">Subscribe Our <span class="text-primary text-uppercase">Newsletter</span></h4>
              <div class="position-relative mx-auto" style="max-width: 400px;">
                <input class="form-control w-100 py-3 ps-4 pe-5" type="text" placeholder="Enter your email" />
                <button type="button" class="btn btn-primary py-2 px-3 position-absolute top-0 end-0 mt-2 me-2">Submit</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Newsletter Start -->

    <!-- Footer Start -->
    {% include 'footer.html' %}
    <!-- Footer End -->

    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
  </div>
{% endblock %}

tolet/templates/all_members.html
{% extends "master.html" %}

{% block title %}
  My Tennis Club - List of all members
{% endblock %}


{% block content %}
  <div class="mycard">
    <h1>Members</h1>
    <ul>
      {% for x in mymembers %}
        <li onclick="window.location = 'details/{{ x.slug }}'">{{ x.firstname }} {{ x.lastname }}</li>
      {% endfor %}
    </ul>
  </div>
{% endblock %}

tolet/templates/base.html
<div class="modal fade" id="exampleModalToggle" aria-hidden="true" aria-labelledby="exampleModalToggleLabel" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalToggleLabel">Login</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          {% include "login.html" %}
        </div>
        <div class="modal-footer">
            <p>If you haven't an account</p>
          <a class=" " href="#" data-bs-target="#exampleModalToggle2" data-bs-toggle="modal" data-bs-dismiss="modal">Registration</a>
        </div>
      </div>
    </div>
  </div>
  <div class="modal fade" id="exampleModalToggle2" aria-hidden="true" aria-labelledby="exampleModalToggleLabel2" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalToggleLabel2">Modal 2</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          {% include "register.html" %}
        </div>
        <div class="modal-footer">
          <button class="btn btn-primary" data-bs-target="#exampleModalToggle" data-bs-toggle="modal" data-bs-dismiss="modal">Back to first</button>
        </div>
      </div>
    </div>
  </div>
  <a class="nav-item nav-link position-absolute top-0 end-0" data-bs-toggle="modal" href="#exampleModalToggle" >Login</a>
  




tolet/templates/main.html
{% extends "master.html" %}

{% block title %}
  ToLet
{% endblock %}

{% block content %}
  <div class="main">
    <h1>ToLet</h1>

    <h3>Members</h3>

    <p>Check out all our <a href="members/">members</a></p>
  </div>
{% endblock %}

tolet/templates/register.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: 'poppins', sans-serif;
          }
          body {
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
            background: url(o.jpg);
            background-size: cover;
            background-position: center;

          }
          .wrapper {
            width: 420px;
            background: transparent;
            border: 2px solid rgba(255, 255, 255, 0.2);
            backdrop-filter: blur(4px);
            box-shadow: 0 0 10px rgba(255, 255, 255, 0.2);
            color: #fff;
            border-radius: 10px;
            padding: 30px 40px;
    </style>
  </head>
  <body>
<div class="form-control " style="border: 2px; border-radius: 2px; border-color: black; background-color: aliceblue; padding: 20px; " >
    <form method="POST" action="">
      {% csrf_token %}
      <h2 style="text-align: center; font-family: 'Courier New', Courier, monospace; padding-bottom: 5px;" >Register</h2>
      <div class="form-group" style="padding-top: 10px; padding-bottom: 10px;" >
        <label for="id_username">Username</label>
        {{ form.username }} <!-- Add class dynamically -->
      </div>

      <div class="form-group" style="padding-top: 10px; padding-bottom: 10px;">
        <label for="id_email">Email</label>
        {{ form.email }} <!-- Add class dynamically -->
      </div>

      <div class="form-group" style="padding-top: 10px; padding-bottom: 10px;">
        <label for="id_password">Password</label>
        {{ form.password1 }} <!-- Add class dynamically -->
      </div>
      <div class="form-group" style="padding-top: 10px; padding-bottom: 10px;">
        <label for="id_password">Password</label>
        {{ form.password2 }} <!-- Add class dynamically -->
      </div>

      <button type="submit" class="btn btn-primary" style="padding-top: 10px; padding-bottom: 10px; align-self: center; ">Submit</button>
    </form>
</div>
  </body>
</html>